/**
 * @file Plaid Link component for initiating account connection
 * @description
 * This component provides a button to open the Plaid Link flow for connecting financial accounts.
 * It uses the usePlaidLink hook from react-plaid-link to manage the connection process.
 *
 * Key features:
 * - Renders a styled button to initiate the Plaid Link flow
 * - Handles the onSuccess callback with public token and metadata
 * - Disables the button until the Plaid Link library is ready
 *
 * @dependencies
 * - react-plaid-link: Provides usePlaidLink hook for Plaid Link integration
 * - react: For component rendering and TypeScript support
 *
 * @notes
 * - Requires a valid link token generated by the server
 * - The onSuccess callback is responsible for submitting the public token and metadata to the server
 * - Styled with Tailwind CSS classes consistent with the dark theme dashboard
 * - Runs client-side only due to DOM interaction via usePlaidLink
 */

import { usePlaidLink } from 'react-plaid-link';

// Define props interface for type safety
interface PlaidLinkProps {
  linkToken: string; // Token from server to initialize Plaid Link
  onSuccess: (publicToken: string, metadata: any) => void; // Callback for successful connection
}

/**
 * Plaid Link component
 * @param linkToken - The link token to initialize Plaid Link
 * @param onSuccess - Callback function called with public token and metadata on success
 * @returns A button that opens the Plaid Link flow when clicked
 */
export default function PlaidLinkComponent({ linkToken, onSuccess }: PlaidLinkProps) {
  // Configure and initialize Plaid Link
  const { open, ready } = usePlaidLink({
    token: linkToken,
    onSuccess, // Triggered when user successfully connects an account
  });

  return (
    <button
      onClick={() => open()} // Opens the Plaid Link modal
      disabled={!ready} // Disabled until Plaid script is loaded
      className="px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 disabled:opacity-50 transition-colors"
    >
      Connect a bank account
    </button>
  );
}